logging:
  level:
    jdbc: DEBUG
    'com.ldz.demo': INFO
spring:
  sql.init:
    platform: ${database_type}
    mode: always
    continue-on-error: true
  jpa:
    show-sql: true
    hibernate:
      # 禁用hibernate自动创表, 使用schema.sql
      ddl-auto: none 
`
if [[ "${database_type}" == "mariadb" ]]; then
echo '
  datasource:
    url: jdbc:mariadb://localhost:3306/tests
    username: root
    password: 
    driver-class-name: org.mariadb.jdbc.Driver
'
fi
`
`
if [[ "${database_type}" == "mysql" ]]; then
echo '
  datasource:
    url: jdbc:mysql://localhost:3306/tests_mysql
    username: root
    password:  
    driver-class-name: com.mysql.cj.jdbc.Driver
'
fi
`
`
if [[ "${database_type}" == "h2" ]]; then
echo '
  h2:
    console:
      enabled: true
      path: /h2-console
  dataSource:
    continue-on-error: true
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE 
    driver-class-name: org.h2.Driver
    username: sa
    password: &quot;&quot;
'
fi
`

jdbc:
  datasource-proxy:
    enabled: true
    query:
      logger-name: jdbc
      enable-logging: true
    multiline: false
    include-parameter-values: true
