alias transz="trans en:zh"
alias transe="trans zh:en"

alias mvninstall="mvn clean install -Dmaven.test.skip=true"
alias mvnsource="mvn dependency:sources -DdownloadJavadocs=true"
alias mvntree="mvn dependency:tree"
alias mvndebug='export MAVEN_OPTS="-Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspen=n"'

# 需要pip3 install pyotp
alias 2fa_git='python -c "import pyotp; print(pyotp.TOTP(\"3NQ2ZK7MF2GQP4LE\").now())"'


proxy () {
    export http_proxy="http://localhost:20181"
    export https_proxy=$http_proxy
    export socks5_proxy="socks5://localhost:20180"
    echo "HTTP Proxy on"
}

# noproxy
noproxy () {
    unset http_proxy
    unset https_proxy
    unset socks5_proxy
    echo "HTTP Proxy off"
}


# 在 Bash shell 中，PS4 是一个环境变量，用来定义在开启 shell 脚本调试模式 (set -x) 时显示的提示符
export PS4='\033[0;33m+ $(date +%T.%3N) $BASH_SOURCE:$LINENO:${FUNCNAME[0]}() :\033[0m '


export JAVA_HOME=/opt/jdk8
export CLASSPATH=.:${JAVA_HOME}/lib/dt.jar:${JAVA_HOME}/lib/tools.jar
export MAVEN_HOME=/opt/apache-maven-3.9.6
export BASH_HOME=~/.local/bin

export LD_LIBRARY_PATH=/home/ldz/.local/lib:$LD_LIBRARY_PATH
export CPPFLAGS="-I/home/ldz/.local/include"
export LDFLAGS="-L/home/ldz/.local/lib"
PATH=.:${JAVA_HOME}/bin:${JAVA_HOME}/jre/bin:${MAVEN_HOME}/bin:${BASH_HOME}:${PATH}

LANG=zh_CN.UTF-8
# 光标不闪烁
printf '\e[?12l'

